export const contactList = [
    {
      id: 1,
      name: "Rahul",
      profilePic: "/profile/ppl1.jpg",
      lastText: "Hey Man",
      lastTextTime: "08:58 PM",
    },
    {
      id: 2,
      name: "Ann",
      profilePic: "/profile/ppl2.jpg",
      lastText: `what going on bro`,
      lastTextTime: "12:45 PM",
    },
    {
      id: 3,
      name: "John Doe",
      profilePic: "/profile/ppl3.jpg",
      lastText: "lets go out?",
      lastTextTime: "09:30 PM",
    },
    {
      id: 4,
      name: "Roshan",
      profilePic: "/profile/ppl4.jpg",
      lastText: "no broo",
      lastTextTime: "12:00 PM",
    },
    {
      id: 5,
      name: "Aarya",
      profilePic: "/profile/ppl5.jpg",
      lastText: "i'm good",
      lastTextTime: "07:20 PM",
    },
    {
      id: 6,
      name: "Manu",
      profilePic: "/profile/ppl6.jpg",
      lastText: "Where ?",
      lastTextTime: "06:04 PM",
    },
    {
      id: 7,
      name: "Amal",
      profilePic: "/profile/ppl7.jpg",
      lastText: "Yes",
      lastTextTime: "11:21 AM",
    },
    {
      id: 8,
      name: "Sebastian",
      profilePic: "/profile/ppl8.jpg",
      lastText: "Hello",
      lastTextTime: "12:00 PM",
    },
    {
      id: 9,
      name: "Fasil",
      profilePic: "/profile/ppl9.jpg",
      lastText: "Hiii",
      lastTextTime: "10:07 AM",
    },
    {
      id: 10,
      name: "Jerrin",
      profilePic: "/profile/ppl10.jpg",
      lastText: "no broo",
      lastTextTime: "03:00 PM",
    },
    
  ];

  
  export const messagesList = [
    {
      id: 1,
      messageType: "message",
      message: "hello",
      replay:"hiiiiiiii",
      senderID: 0,
      addedOn: "12:00 PM",
    },
    {
      id: 2,
      messageType: "message",
      message: "What's up?",
      replay: "fine ....",
      senderID: 1,
      addedOn: "12:01 PM",
    },
    {
      id: 3,
      messageType: "message",
      message: "Hello Whatsup ",
      replay: "good what about you",
      senderID: 0,
      addedOn: "12:00 PM",
    },
    {
      id: 4,
      messageType: "message",
      message: "What about you",
      replay: "I'm good as well",
      senderID: 1,
      addedOn: "12:00 PM",
    },
    {
      id: 5,
      messageType: "message",
      message: "Ok ?",
      replay: "Great 😁",
      senderID: 0,
      addedOn: "12:00 PM",
    },
    {
      id: 6,
      messageType: "message",
      message: "Hiii",
      replay: "mmmm",
      senderID: 1,
      addedOn: "12:00 PM",
    },
    {
      id: 7,
      messageType: "message",
      message: "let's go",
      replay: "ok ",
      senderID: 1,
      addedOn: "12:00 PM",
    },
    {
      id: 8,
      messageType: "message",
      message: "hello",
      replay: "hiiii",
      senderID: 1,
      addedOn: "12:00 PM",
    },
    {
      id: 9,
      messageType: "message",
      message: "How are you today ?",
      replay : "I'm good",
      senderID: 1,
      addedOn: "12:00 PM",
    },
    {
      id: 10,
      messageType: "message",
      message: "How are you today ?",
      replay: "fine",
      senderID: 1,
      addedOn: "12:00 PM",
    },
    
  ];